### ISSUE TITLE
Hours page PDF link bug

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-redesign#264] opened 2020-01-08 19:14 UTC
In the Regular Hours section of the Hours index page, the PDF link included in the text "For a more detailed summary of semester hours, please view or download the (PDF)" doesn't change when choosing a different semester the "Displaying regular hours for (semester)." 

![Hours PDF issue.JPG](https://images.zenhubusercontent.com/5df7babf7b5b6937b5601871/32f37f45-b869-4206-8733-b105db8a32a7)

I tested changing the order of the semesters in the Woodruff Library Building hours page. Whichever semester comes first in the list appears at the top of the drop down, and the associated PDF link remains, even after choosing another semester.

**Comment by kristianserrano** [comment] 2020-01-10 14:39
@cwbragg and @rosy1280, after testing in the pattern library with updated data, I can confirm that this is actually working as expected. I'm unable to duplicate the results observed on the site. 

I suspect the issue is with how the Velocity for the hours page is writing the Vue component. I'm crawling through the Velocity, and I'm noticing some differences that could possibly be preventing matching between the data of the pill button selected and the other data in the Vue template itself. 

I've made test copies of both the Velocity and the hours page inside of a dev folder in Emory Libraries - Template Assets in Cascade so that I can continue investigating.

I'll update this once I've discovered the actual source of the problem.

**Comment by kristianserrano** [comment] 2020-01-10 17:17
@rosy1280 and @cwbragg, I think I've found the problem. The Velocity is applying the same URL for the full hours PDF link as it loops through the locations. They all have the same URL, so technically it's changing to the same value.

You can observe this by viewing the page source and searching for
`/_shared/hours/fall-intersession-2019-20-web.pdf`.

**Comment by kristianserrano** [comment] 2020-01-10 18:29
Making notes here to clarify for myself:

1. The full hours PDF _is not_ supposed to change when a different location is selected. This is working as expected on the site, but not in the pattern library. @rosy1280 do we need to change this in the pattern library to reflect this behavior?
2. The full hours PDF _is_ supposed to change when the semester is changed. This is working as expected in the pattern library, but not on the site.

**Comment by kristianserrano** [comment] 2020-01-10 19:19
@rosy1280 per our discussion in your office, I have the understanding that the issue on the site (item #2 above) is something for HH to address. Can you verify? Thanks!

**Comment by rosy1280** [comment] 2020-01-15 20:54
@kristianserrano yes item 2 is something HH should address.  

Additionally, we should change the pattern library so that the full hours PDF which appears next to the semester dropdown as "For a more detailed summary of semester hours, please view or download the Full Schedule of Hours." does not change when a different location is selected. This is working as expected on the site, but not in the pattern library.

**Comment by rosy1280** [comment] 2020-01-15 20:58
@kristianserrano i also assigned this ticket to me so i can track the HH work.  if you finish before they finish, just unassign yourself and i'll close it (and also the opposite is true if they finish first).

**Comment by kristianserrano** [comment] 2020-01-15 21:47
@rosy1280 I'll start working on the static full schedule link and text.

**Comment by kristianserrano** [comment] 2020-01-16 20:01
@rosy1280 I've made the changes to the pattern library so that the full schedule PDF links are tied to the given semester. These links change only when the semester changes.

I also fixed the issue in the pattern library where it was duplicating semesters.

You can see both of these changes on the [template for the hours page in the pattern library](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/60-templates-hours-hours/60-templates-hours-hours.html).

HH will need to update the Velocity formats to make the necessary modifications for the Vue template. The commit for this change can be seen here:
https://github.com/emory-libraries/Pattern-Library/commit/3a67b11bc1dd8df9519a83f89584c1a4608c82df

**Comment by kristianserrano** [comment] 2020-01-16 20:42
@rosy1280 We'll need to deploy the updated JS before HH puts the Velocity changes in, otherwise if the hours page deploys without the updated script for the hours page, the semester selection might not render correctly. We also need to be mindful that we have nightly publishings of the whole site and the hours page to both destinations.

There are two possible solutions:

1. We notify HH when the JS has been deployed, at which point they are safe to add the changes to the Velocity in our Cascade template. This option means less work for HH but does require coordination.
2. HH temporarily adds a check in the Vue templating for `uniqueSemesters` which the new script creates. If that value is `undefined` then it could use the old Vue template, but if it's `!undefined`, it will render the new Vue template. This option adds a bit more work for HH, but they would be free to update our template whenever they'd like.

I recommend option 1 as it gives us a bit more control and stability and reduces risks for error. Additionally, option 2 would require post-deployment clean up in the Velocity.

**Comment by rosy1280** [comment] 2020-01-17 22:53
@kristianserrano if you could re-deploy this on Monday that would be great.  It looks like HH hasn't picked up the ticket yet (and aren't likely to before Monday because its 6pm on Friday)

**Comment by kristianserrano** [comment] 2020-01-17 23:39
@rosy1280 just wanted to verify two things:

1. Do you actually mean Monday or Tuesday? (Is HH working during the holiday?)
2. Do you mean specifically a final tagged release for production?

In any of those cases, yes, I can.

**Comment by rosy1280** [comment] 2020-01-18 00:36
@kristianserrano sorry yes I meant Tuesday and yes an official tagged release.

**Comment by kristianserrano** [comment] 2020-01-18 00:38
@rosy1280 will do.

**Comment by kristianserrano** [comment] 2020-01-21 17:07
@rosy1280 I’ve tagged and released v1.0.4 which includes the fix for the hours page.

**Comment by rosy1280** [comment] 2020-02-14 22:06
@kristianserrano this currently indicates that its blocked.  i don't believe that is the case but just wanted to check in before i close the issue

**Comment by kristianserrano** [comment] 2020-02-14 22:13
@rosy1280 If HH made the changes necessary in the Velocity and it's working as expected on the site, then it shouldn't be blocked anymore.

**Closed as completed** 2020-02-14 22:32 UTC
Labels: bug, Production Launch
