### ISSUE TITLE
Reevaluate Roles and Permissions in Cascade

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#30] opened 2018-12-03 19:28 UTC
Since roles and permissions were created during Phase 1, a reevaluation of these roles and permissions is needed.

**Comment by kristianserrano** [comment] 2019-05-09 17:46
I mentioned this in #29, but...

I'm pretty sure we've got this done but just didn't note it.

What is missing though is the removal of content producers from the `Library - Main - Publish to Production` group if we want to keep content producers from being able to publish to production.

We'll also want to remove producers from `Library - New Asset Creators` if we want to restrict them from making new pages.

Should that be a separate issue?

**Comment by kristianserrano** [comment] 2019-05-09 19:00
Two additional considerations:

1. We'll need to consider giving the ability for producers to use asset factories to upload images and documents into the appropriate folders but not being able to create new pages. One solution might be to grant access to those two asset factories to the `Library - Main - Publish to Staging` group.

2. Do we want to add restrictions on producers that prevent them from being able to move/rename/delete existing pages? It could help with preventing broken links due to lack of redirects or linked pages not being republished with the updated URL. On the other hand, documentation and training could cover that, but there's the risk they might not remember to take care of those things.

**Comment by laurenhamel** [comment] 2019-05-14 15:21
I also wanted to add some notes in regards to some of the offline discussions that @kristianserrano and I have had. Some other things that came up related to permissions:

- Defining redirects - This is likely something that producers shouldn't be able to touch freely
- Shared/global data - This may affect multiple sites and/or pages, so how do we manage it?

**Comment by nikdragovic** [comment] 2019-07-10 01:14
@kristianserrano Can we move this into a post-launch sprint?

**Comment by laurenhamel** [comment] 2019-11-07 16:56
Like #29, the initial assignment of roles, groups, and permissions has been completed, but it may be worthwhile to reassess the completeness of this at some point closer to launch when things are more final. More clarification around what this may look like is needed.

**Comment by laurenhamel** [comment] 2019-11-07 20:15
Closing as a duplicate of #29.

**Closed by laurenhamel** 2019-11-07 20:15 UTC
Labels: Content Governance, Operations, question
